"""user createdAt

Revision ID: cb91dd2a3bcb
Revises:
Create Date: 2023-07-23 16:57:25.247331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb91dd2a3bcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('snippet', sa.String(), nullable=False),
                    sa.Column('keywords', sa.PickleType(), nullable=False),
                    sa.Column('createdAt', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=30), nullable=False),
                    sa.Column('full_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('createdAt', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('business')
    # ### end Alembic commands ###
